// Check command for the custom needrestart plugin.
// The apt CheckCommand is provided by the Icinga2 ITL (<plugins>).
object CheckCommand "needrestart" {
    command = [ "/usr/lib/nagios/plugins/check_needrestart" ]
}
