object ApiUser "autoupdate" {
    password = "Pain-Frequently-Mother-Sun3-Instead"
    permissions = [
        "status/query",
        "objects/query/Host",
        "objects/query/Service",
        "objects/query/Downtime",
        "actions/schedule-downtime",
        "actions/remove-downtime",
        "actions/reschedule-check",
        "actions/process-check-result",
    ]
}
